### PR TITLE
[ClassicFlang][Driver] Correct the LLVM version passed by the Driver

### PR DESCRIPTION
**Pull request by SouraVX**

### CODE REVIEW

**Comment by SouraVX** [comment]
I noticed this while investigating build failures of https://github.com/flang-compiler/flang/pull/898
To be precise, this bounce check is failing `if (ll_feature_debug_info_ver11(&db->module->ir)) {` due to value `90` passed by the Driver causing the flang to add the version 11 based DebugInfo and finally the `testcase` failure :(

**Comment by SouraVX** [comment]
After making this change, I'm also observing failures while building `flang` (could be spurious?)
```
[ 28%] Building C object runtime/flang/CMakeFiles/flang_static.dir/dbesjn3f.c.o
/tmp/iso_c_bind-50b995.ll:44:17: error: expected comma after load's type
        %0 = load i64* %a, align 8, !tbaa !30, !dbg !24
```
Making me think, is this version `90` was kept as it is for a reason ?
                       ^
1 error generated.

**Comment by SouraVX** [comment]
CI is failing while building LLVM itself :(, Looking it log seems un-related to this change + At least LLVM Build is passing locally
@michalpasztamobica Any pointer that can help ?

File: clang/lib/Driver/ToolChains/ClassicFlang.cpp [hunk 1]
```diff
@@ -955,7 +955,7 @@ void ClassicFlang::ConstructJob(Compilation &C, const JobAction &JA,
   LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("121"); LowerCmdArgs.push_back("0x800");
   LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("54"); LowerCmdArgs.push_back("0x10");
   LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("70"); LowerCmdArgs.push_back("0x40000000");
-  LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("249"); LowerCmdArgs.push_back("90"); // LLVM version
+  LowerCmdArgs.push_back("-x"); LowerCmdArgs.push_back("249"); LowerCmdArgs.push_back("11"); // LLVM version
```
Comment (bryanpkc) [inline clang/lib/Driver/ToolChains/ClassicFlang.cpp]: Shouldn't this be changed to `"110"` instead of `"11"`? Unless you are also changing the way it is used in flang.

Comment (SouraVX) [reply clang/lib/Driver/ToolChains/ClassicFlang.cpp]: Thanks for catching this :) While moving back & forth with clang & flang I forgot the convention.
All builds are clean (locally)  https://github.com/flang-compiler/flang/pull/898 this should also pass after this change

**Comment by SouraVX** [comment]
Let's see how CI reacts :)

**Comment by SouraVX** [comment]
CI fails here, however its passing in #46 & #47. @michalpasztamobica any pointers/insights you may share ?
Thanks!

**Comment by michalpasztamobica** [comment]
Hi @SouraVX , you have came across the same error I just fixed in https://github.com/flang-compiler/classic-flang-llvm-project/pull/42:
```
In file included from /home/runner/work/classic-flang-llvm-project/classic-flang-llvm-project/llvm/utils/benchmark/src/benchmark_register.cc:15:
/home/runner/work/classic-flang-llvm-project/classic-flang-llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: no member named 'numeric_limits' in namespace 'std'
```

Please, try to rebase on top of that fix - that should solve the problem.

**Review by michalpasztamobica — APPROVED** [review]

**Comment by SouraVX** [comment]
@bryanpkc & @kiranchandramohan If we can agree/(reach approval) on this, it will clear the roadblock of version specific dependency of the DebugInfo PR's such as https://github.com/flang-compiler/flang/pull/898 :)
Thanks!

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by SouraVX** [comment]
From ARM side we have @michalpasztamobica approval. Is it Okay to merge this ?

**Comment by kiranchandramohan** [comment]
Yes.
